server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: sisimpur-library
  datasource:
    url: jdbc:postgresql://localhost:5433/sisimpur
    username: halum
    password: machvaja
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 1
