ALTER TABLE books
    ADD COLUMN is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE authors
    ADD COLUMN is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN is_active BOOLEAN DEFAULT TRUE;

